# Generated by Django 3.0.6 on 2020-07-07 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='email',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(default='home', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(default='city', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(default='bm', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='zip_code',
            field=models.CharField(default='84848', max_length=20),
            preserve_default=False,
        ),
    ]
