# Generated by Django 3.0.6 on 2020-07-07 01:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200707_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='order',
            name='ordred_time',
            field=models.TimeField(default=datetime.time(1, 30, 14, 234529)),
        ),
    ]
