# Generated by Django 3.0.6 on 2020-07-07 01:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20200707_0130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ordred_time',
        ),
        migrations.AddField(
            model_name='order',
            name='ordered_time',
            field=models.TimeField(default=datetime.time(1, 34, 11, 612228)),
        ),
    ]
