# Generated by Django 3.0.6 on 2020-07-07 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20200707_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_time',
            field=models.TimeField(default=datetime.time(15, 4, 58, 411833)),
        ),
    ]
