# Generated by Django 3.0.6 on 2020-07-13 03:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20200707_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='phone',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_time',
            field=models.TimeField(default=datetime.time(3, 18, 56, 946807)),
        ),
    ]
